name: Build and Test

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ secrets.CACHE_BUSTER }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-${{ secrets.CACHE_BUSTER }}
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  test:
    name: Test
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ secrets.CACHE_BUSTER }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node_modules-${{ secrets.CACHE_BUSTER }}
      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
