name: Deploy

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  download-artifacts:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-and-test.yml
          workflow_conclusion: success
          name: build-artifacts
          path: build

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          draft: true,
          comment-on-pull-request: true
