name: Deploy

# only trigger on pull request closed events
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  download-artifacts:
    name: Deploy artifacts
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
