name: Deploy

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed

jobs:
  download-artifacts:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-and-test.yml
          workflow_conclusion: success
          name: build-artifacts
          path: build

      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --alias ${{ env.GITHUB_REF_NAME }} 
